### ISSUE TITLE
pass error as first argument in callback

### ISSUE THREAD

**Issue by avetisk** [node-gitlab/node-gitlab-legacy#76]
This would make `my|their` life much easier :)

``` javascript
gitlab.projects.create({
  // ...
}, function onSuccess (err, result) {
  if (err) {
    // handle error here
  }}
});
```

**Comment by moul** [comment]
It is actually handled; we are calling the callback with different arguments depending of the amount of arguments it takes

Take a look at: https://github.com/node-gitlab/node-gitlab/blob/master/src/ApiBaseHTTP.coffee#L45-L48

Depending on the amount or arguments your callback takes (arity):
- with 1 argument, you get only the json result of the API call
- with 2 arguments, you get the error (if any), then the json result
- with 3 arguments, you get the error (if any), then the response (with http headers etc), then the json result

**Comment by dave-irvine** [comment]
@moul Should we just always expect the callback to be of the form

`function x (err, ...)`

I think this is the "de facto" standard for node?

**Comment by moul** [comment]
We can remove or mark as deprecated with a warning the callbacks with `arity=1` yes
`arity=2` mimics the standard for node

Go for it ? :)

**Comment by avetisk** [comment]
@moul: using @dave-irvine proposal sounds better.

As sometimes you won't except any result but you would expect some errors.

**Comment by moul** [comment]
@avetisk I think I was not clear :)

my proposal is the same as @dave-irvine 

removing `arity=1` means remove the only kind of callback without err as argument, so we keep : 

- `arity=2`: `function x (err, ret) {}`
- `arity=3`: `function x (err, ret, response) {}`

Does it make more sense ?

**Comment by avetisk** [comment]
@moul in that case, it may be a bit of annoying for some developers.

For instance, if I only need `err` but I add `ret` for the sake of the callback's signature, I would need also to add a comment for my linter to tell it to ignore the unused variable.

IMO, the best would be to always use the last signature (`err`, `ret`, `response`).

**Comment by moul** [comment]
Yes ok, I agree

Since it will break completely the current compatibility we need to discuss if we can take advantage of this refactor to add more features like promises

I looked at this library https://github.com/jakutis/httpinvoke, it permits to use promises but also to use standard callbacks, we can imagine to switch slumber with httpinvoke or since I maintain slumber, I can try to update slumber to add promises

@dave-irvine what do you think about this arguments/functions/arity global refactoring ?
What do you think about trying to get promises working too ?
I think we will need to upgrade node-gitlab major version since it completely break the actual compatibility

Another option is to add an option in the initialization of the API so we can choose to keep arity/based callbacks, switch to standard node callbacks or use promises

**Comment by dave-irvine** [comment]
I think we should just stop testing for arity and call the callback like:

cb(err, ret, response).

`err` should be null if no error has occured.
`ret` should always be the parsed JSON response unless an error, then empty object `{}`, because in some error cases there is no valid JSON to parse.
`response` should always be the full http response, even if an error, so that you can figure out what the error is later on.

If the arity is actually 2, there is no problem, JS will just drop the `response` parameters, no harm done.

**Comment by dave-irvine** [comment]
@moul Shall we switch to https://gitter.im/node-gitlab/node-gitlab temporarily to discuss this?

**Comment by moul** [comment]
@dave-irvine today I can't but yes for tomorrow, with great pleasure ;)

**Comment by dcolens** [comment]
the above code assumes the original callback function is passed to `ApiBaseHTTP.prototype.fn_wrapper`, however in the above example it is not the case, the `Projects.prototype.create` method passes this function :
```function(data) {
        if (fn) {
          return fn(data);
        }
      } ```

which takes a single argument and `arity` is always 1 regardless of the number of args in the callback :(

Could you fix this bug ?

Thanks,

Did

**Comment by Kamshak** [comment]
Any news on this? Very annoying for Promisification

**Comment by dave-irvine** [comment]
This is roadmapped for a 2.0 release, no timetable yet unfortunately.

**Comment by fuhbar** [comment]
Under #123 I've opened a new issue regarding the question @dcolens mentioned. This relates partly to the topic discussed here and should not - at least in my opinion - wait till 2.0 release, since error handling seems to be broken here.

**Comment by ry60003333** [comment]
Any updates on this? I'm currently experiencing issues where my Node app occasionally crashes with the following error:
```
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at /Users/ry60003333/NetBeansProjects/StatusBoard/node_modules/gitlab/lib/ApiBaseHTTP.js:88:42
    at _Class.wrap_response (/Users/ry60003333/NetBeansProjects/StatusBoard/node_modules/gitlab/node_modules/slumber/lib/API.js:192:18)
    at _Class.wrap_response (/Users/ry60003333/NetBeansProjects/StatusBoard/node_modules/gitlab/node_modules/slumber/lib/API.js:4:59)
    at Request._callback (/Users/ry60003333/NetBeansProjects/StatusBoard/node_modules/gitlab/node_modules/slumber/lib/API.js:215:26)
    at Request.self.callback (/Users/ry60003333/NetBeansProjects/StatusBoard/node_modules/gitlab/node_modules/slumber/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/ry60003333/NetBeansProjects/StatusBoard/node_modules/gitlab/node_modules/slumber/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
```

I am unable to handle this error with callbacks as the above comments have stated, and end up having to manually restart the app. If anyone has another workaround that I should be using I am open to suggestions!

**Comment by qeesung** [comment]
+1 Node process crashed when I input wrong token.
